/* 
 * WebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using WebApi;
using WebApi.Client;

namespace WebApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IWeatherForecastApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;WeatherForecast&gt;</returns>
        List<WeatherForecast> WeatherForecastGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;WeatherForecast&gt;</returns>
        ApiResponse<List<WeatherForecast>> WeatherForecastGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;WeatherForecast&gt;</returns>
        System.Threading.Tasks.Task<List<WeatherForecast>> WeatherForecastGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;WeatherForecast&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<WeatherForecast>>> WeatherForecastGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class WeatherForecastApi : BaseApi, IWeatherForecastApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WeatherForecastApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WeatherForecastApi(String basePath) : base(basePath)
        {

        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WeatherForecastApi"/> class
        /// </summary>
        /// <returns></returns>
        public WeatherForecastApi() : base()
        {

        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WeatherForecastApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WeatherForecastApi(WebApi.Client.Configuration configuration = null) : base(configuration)
        {

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;WeatherForecast&gt;</returns>
        public List<WeatherForecast> WeatherForecastGet ()
        {
             ApiResponse<List<WeatherForecast>> localVarResponse = WeatherForecastGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;WeatherForecast&gt;</returns>
        public ApiResponse<List<WeatherForecast>> WeatherForecastGetWithHttpInfo ()
        {

            var localVarPath = "/WeatherForecast";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WeatherForecastGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<WeatherForecast>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<WeatherForecast>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<WeatherForecast>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;WeatherForecast&gt;</returns>
        public async System.Threading.Tasks.Task<List<WeatherForecast>> WeatherForecastGetAsync ()
        {
             ApiResponse<List<WeatherForecast>> localVarResponse = await WeatherForecastGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="WebApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;WeatherForecast&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<WeatherForecast>>> WeatherForecastGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/WeatherForecast";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WeatherForecastGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<WeatherForecast>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<WeatherForecast>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<WeatherForecast>)));
        }

    }
}
